import React,{useEffect,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
type Req={id:string;project_id:string;type:string;libelle:string;montant_centimes:number;motif:string;statut:string;commentaire_decision:string|null;piece_jointe_path:string|null};
export default function FinanceRequestsPanel({db,role,exerciseId,onUpdated}:{db:SupabaseClient;userId:string;role:string;exerciseId:string;onUpdated:()=>Promise<void>}){
 const[rows,setRows]=useState<Req[]>([]),[names,setNames]=useState<Record<string,string>>({}),[notes,setNotes]=useState<Record<string,string>>({}),[busy,setBusy]=useState(''),[msg,setMsg]=useState('');
 const canDecide=['superadmin','tresorier','vice_tresorier'].includes(role);
 const load=async()=>{const [r,p]=await Promise.all([db.from('apel_finance_requests').select('*').order('created_at',{ascending:false}),db.from('projects').select('id,title')]);if(r.error)setMsg(r.error.message);else setRows(r.data||[]);if(!p.error)setNames(Object.fromEntries((p.data||[]).map(x=>[x.id,x.title])))};
 useEffect(()=>{void load()},[db]);
 const openFile=async(path:string)=>{const {data,error}=await db.storage.from('apel-request-files').createSignedUrl(path,60);if(error||!data){setMsg(error?.message||'Document inaccessible');return}window.open(data.signedUrl,'_blank','noopener,noreferrer')};
 const decide=async(id:string,approve:boolean)=>{const note=(notes[id]||'').trim();if(!approve&&note.length<5){setMsg('Motif du refus obligatoire (5 caractères minimum).');return}if(approve&&!exerciseId){setMsg('Sélectionne un exercice.');return}setBusy(id);const {error}=await db.rpc('apel_decide_finance_request',{p_request_id:id,p_approve:approve,p_comment:note,p_exercice_id:approve?exerciseId:null});setBusy('');if(error){setMsg(error.message);return}setMsg(approve?'Validée : écriture créée, non réglée.':'Refus transmis.');await load();await onUpdated()};
 return <section className="finance-panel"><h2>Demandes à valider</h2><p>Une validation crée une écriture non réglée : elle ne modifie pas la trésorerie.</p>{msg&&<p role="status">{msg}</p>}{rows.map(r=><article key={r.id} className="finance-request"><strong>{r.libelle} — {(r.montant_centimes/100).toFixed(2)} €</strong><p>{r.type==='depense'?'Dépense':'Recette'} · {names[r.project_id]||'Opération'} · {r.statut}</p><p>{r.motif}</p>{r.piece_jointe_path&&<button type="button" onClick={()=>void openFile(r.piece_jointe_path!)}>Consulter le justificatif</button>}{r.commentaire_decision&&<p>Décision : {r.commentaire_decision}</p>}{r.statut==='en_attente'&&canDecide&&<><label>Commentaire<textarea value={notes[r.id]||''} onChange={e=>setNotes(x=>({...x,[r.id]:e.target.value}))}/></label><div className="finance-actions"><button disabled={busy===r.id||!exerciseId} onClick={()=>void decide(r.id,true)}>Valider</button><button disabled={busy===r.id} onClick={()=>void decide(r.id,false)}>Refuser</button></div></>}</article>)}{rows.length===0&&<p>Aucune demande.</p>}</section>;
}
