import React,{useEffect,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
type Req={id:string;type:string;libelle:string;montant_centimes:number;statut:string;commentaire_decision:string|null};
export default function OperationRequestsPanel({db,userId,projectId}:{db:SupabaseClient;userId:string;projectId:string}){
 const[rows,setRows]=useState<Req[]>([]),[kind,setKind]=useState('depense'),[label,setLabel]=useState(''),[amount,setAmount]=useState(''),[note,setNote]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[file,setFile]=useState<File|null>(null);
 const load=async()=>{const {data,error}=await db.from('apel_finance_requests').select('id,type,libelle,montant_centimes,statut,commentaire_decision').eq('project_id',projectId).order('created_at',{ascending:false});if(error)setMsg(error.message);else setRows(data||[])};
 useEffect(()=>{void load()},[db,projectId]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();const value=Math.round(Number(amount.replace(',','.'))*100);if(!Number.isSafeInteger(value)||value<=0){setMsg('Montant invalide');return}setBusy(true);const {data,error}=await db.from('apel_finance_requests').insert({project_id:projectId,type:kind,libelle:label.trim(),montant_centimes:value,motif:note.trim(),requested_by:userId}).select('id').single();if(error){setBusy(false);setMsg(error.message);return}if(file&&data){const path=`${data.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const upload=await db.storage.from('apel-request-files').upload(path,file,{contentType:file.type});if(upload.error){setMsg('Demande créée, justificatif non joint : '+upload.error.message)}else{const {error:attachError}=await db.rpc('apel_attach_request_file',{p_request_id:data.id,p_path:path});if(attachError)setMsg('Demande créée, justificatif non lié : '+attachError.message)}}setBusy(false);if(error){setMsg(error.message);return}setLabel('');setAmount('');setNote('');setFile(null);setMsg(x=>x.startsWith('Demande créée,')?x:'Demande transmise au trésorier.');void load()};
 return <div className="op-requests"><form onSubmit={submit}><label>Nature<select value={kind} onChange={e=>setKind(e.target.value)}><option value="depense">Demande de frais</option><option value="recette">Déclaration de recette</option></select></label><label>Objet<input required minLength={2} value={label} onChange={e=>setLabel(e.target.value)}/></label><label>Montant (€)<input required type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Motif<textarea required minLength={5} value={note} onChange={e=>setNote(e.target.value)}/></label><label>Justificatif facultatif (PDF, JPG, PNG, 10 Mo maximum)<input type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={e=>{const f=e.target.files?.[0]||null;if(f&&(!['application/pdf','image/jpeg','image/png'].includes(f.type)||f.size>10485760)){setMsg('Format ou taille invalide');setFile(null)}else setFile(f)}}/></label><button disabled={busy}>Envoyer au trésorier</button></form>{msg&&<p role="status">{msg}</p>}<h4>Demandes</h4>{rows.map(r=><div className="op-request-row" key={r.id}><strong>{r.libelle}</strong> · {(r.montant_centimes/100).toFixed(2)} € · {r.statut}{r.commentaire_decision&&<p>Réponse : {r.commentaire_decision}</p>}</div>)}</div>;
}
