import React,{useEffect,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
import {Plus,CheckCircle2,ArrowRight} from 'lucide-react';
import './operations.css';
type P={db:SupabaseClient;userId:string;role:string;initialIdeaId?:string|null;onConverted?:()=>void};
type Idea={id:string;title:string;description:string|null;status:string;author_id:string|null;contact_name:string|null;source:string;created_at:string};
type Project={id:string;title:string;description:string|null;status:string;budget:number|null;owner_id:string|null;idea_id:string|null;deadline:string|null};
type Task={id:string;title:string;status:string;due_date:string|null;assignee_id:string|null;project_id:string|null};
type TaskDraft={title:string;assignee_id:string;due_date:string};
const blankTask=():TaskDraft=>({title:'',assignee_id:'',due_date:''});
type Member={id:string;full_name:string};
type Comment={id:string;idea_id:string;author_id:string;body:string;created_at:string};
const euro=(n:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(n);
export default function OperationsModule({db,userId,role,initialIdeaId,onConverted}:P){
 const [ideas,setIdeas]=useState<Idea[]>([]),[projects,setProjects]=useState<Project[]>([]),[members,setMembers]=useState<Member[]>([]),[tasks,setTasks]=useState<Task[]>([]),[comments,setComments]=useState<Comment[]>([]);
 const [selectedIdea,setSelectedIdea]=useState<Idea|null>(null),[selectedProject,setSelectedProject]=useState<Project|null>(null);
 const [showCreate,setShowCreate]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const [draft,setDraft]=useState({title:'',description:'',owner_id:'',deadline:'',budget:'0',members:[] as string[],volunteers:'',tasks:[blankTask()]});
 const [comment,setComment]=useState('');
 const [operations,setOperations]=useState<{project_id:string|null;type:string;montant_centimes:number;statut:string}[]>([]);
 const canSeeFinance=['superadmin','president','vice_president','tresorier','vice_tresorier'].includes(role);
 const isManager=['superadmin','president','vice_president','secretaire','vice_secretaire','tresorier','vice_tresorier'].includes(role);
 const reload=async()=>{
  const [i,p,m,t,o]=await Promise.all([db.from('ideas').select('id,title,description,status,author_id,contact_name,source,created_at').order('created_at',{ascending:false}),db.from('projects').select('id,title,description,status,budget,owner_id,idea_id,deadline').order('created_at',{ascending:false}),db.from('profiles').select('id,full_name').eq('active',true),db.from('tasks').select('id,title,status,due_date,assignee_id,project_id'),canSeeFinance?db.from('finance_operations').select('project_id,type,montant_centimes,statut'):Promise.resolve({data:[],error:null})]);
  if(i.error||p.error||t.error){setMessage((i.error||p.error||t.error)?.message||'Chargement impossible');return}
  setIdeas(i.data||[]);setProjects(p.data||[]);setMembers(m.data||[]);setTasks(t.data||[]);if(!o.error)setOperations(o.data||[]);
  if(initialIdeaId){const target=(i.data||[]).find(x=>x.id===initialIdeaId);if(target)setSelectedIdea(target)}
 };
 useEffect(()=>{void reload()},[db]);
 useEffect(()=>{if(!selectedIdea){setComments([]);return}db.from('idea_comments').select('*').eq('idea_id',selectedIdea.id).order('created_at',{ascending:true}).then(({data,error})=>{if(error)setMessage(error.message);else setComments(data||[])})},[db,selectedIdea?.id]);
 const start=(idea?:Idea)=>{setSelectedIdea(null);setDraft({title:idea?.title||'',description:idea?.description||'',owner_id:userId,deadline:'',budget:'0',members:[],volunteers:'',tasks:[blankTask()]});setShowCreate(true);};
 const convert=async(e:React.FormEvent)=>{e.preventDefault();if(busy)return;if(!draft.owner_id||!draft.title.trim()){setMessage('Nom et responsable obligatoires.');return}const budget=Number(draft.budget.replace(',','.'));if(draft.tasks.some(t=>t.title.trim()&&(!t.assignee_id||!t.due_date))){setMessage('Chaque tâche doit avoir un responsable et une échéance.');return}if(!Number.isFinite(budget)||budget<0){setMessage('Budget invalide.');return}setBusy(true);setMessage('');
  const {data,error}=await db.rpc('create_apel_operation_v2',{p_title:draft.title.trim(),p_description:draft.description||null,p_owner:draft.owner_id,p_deadline:draft.deadline||null,p_budget_centimes:Math.round(budget*100),p_idea_id:convertIdea?.id||null,p_members:draft.members,p_volunteers:draft.volunteers.split(',').map(x=>x.trim()).filter(Boolean),p_tasks:draft.tasks.filter(x=>x.title.trim()).map(x=>({title:x.title.trim(),assignee_id:x.assignee_id||null,due_date:x.due_date||null}))});
  setBusy(false);if(error){setMessage('Création impossible : '+error.message);return}setShowCreate(false);setConvertIdea(null);setMessage('Opération créée et reliée à la finance.');void reload();onConverted?.();
 };
 const [convertIdea,setConvertIdea]=useState<Idea|null>(null);
 const postComment=async(e:React.FormEvent)=>{e.preventDefault();if(!selectedIdea||!comment.trim())return;const {error}=await db.from('idea_comments').insert({idea_id:selectedIdea.id,author_id:userId,body:comment.trim()});if(error){setMessage(error.message);return}setComment('');const {data}=await db.from('idea_comments').select('*').eq('idea_id',selectedIdea.id).order('created_at',{ascending:true});setComments(data||[])};
 const updateTask=async(t:Task,status:string)=>{const {error}=await db.from('tasks').update({status}).eq('id',t.id);if(error)setMessage(error.message);else setTasks(old=>old.map(x=>x.id===t.id?{...x,status}:x))};
 const addTask=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!selectedProject)return;const input=(e.currentTarget.elements.namedItem('task') as HTMLInputElement);const title=input.value.trim();if(!title)return;const form=e.currentTarget;const assignee=(form.elements.namedItem('assignee') as HTMLSelectElement).value;const due=(form.elements.namedItem('due') as HTMLInputElement).value;const {error}=await db.from('tasks').insert({project_id:selectedProject.id,title,status:'À faire',assignee_id:assignee||null,due_date:due||null});if(error)setMessage(error.message);else{input.value='';void reload()}};
 const setProjectStatus=async(p:Project,status:string)=>{const {error}=await db.from('projects').update({status}).eq('id',p.id);if(error)setMessage(error.message);else{setProjects(old=>old.map(x=>x.id===p.id?{...x,status}:x));setSelectedProject({...p,status})}};
 return <section className="op-module"><div className="op-heading"><div><div className="eyebrow">PILOTAGE ASSOCIATIF</div><h1>Opérations</h1><p className="lead">Transformez les idées en actions concrètes, puis suivez les tâches et les finances.</p></div>{isManager&&<button className="primary" onClick={()=>{setConvertIdea(null);start()}}><Plus size={17}/> Nouvelle opération</button>}</div>{message&&<p className="op-notice" role="status">{message}</p>}
 <div className="op-section"><h2>Idées à examiner</h2><div className="op-grid">{ideas.filter(i=>!projects.some(p=>p.idea_id===i.id)).map(i=><article key={i.id} className="op-card"><span className="tag">{i.status}</span><h3>{i.title}</h3><p>{i.description||'Aucune description'}</p><small>Référent : {i.source==='public'?(i.contact_name||'Parent'):members.find(m=>m.id===i.author_id)?.full_name||'Membre du bureau'}</small><button className="textbutton" onClick={()=>setSelectedIdea(i)}>Voir et commenter <ArrowRight size={15}/></button></article>)}{ideas.length===0&&<p>Aucune idée enregistrée pour le moment.</p>}</div></div>
 <div className="op-section"><h2>Opérations en cours et archivées</h2><div className="op-grid">{projects.map(p=>{const ts=tasks.filter(t=>t.project_id===p.id);const paid=operations.filter(o=>o.project_id===p.id&&o.statut==='paye');const receipts=paid.filter(o=>o.type==='recette').reduce((a,o)=>a+o.montant_centimes,0)/100;const expenses=paid.filter(o=>o.type==='depense').reduce((a,o)=>a+o.montant_centimes,0)/100;return <article key={p.id} className="op-card"><span className="tag">{p.status}</span><h3>{p.title}</h3><p>{p.description||''}</p><p>Responsable : {members.find(m=>m.id===p.owner_id)?.full_name||'À définir'}</p><p>Échéance : {p.deadline||'Non définie'}</p>{canSeeFinance&&<div className="op-finance"><span>Budget {euro(Number(p.budget||0))}</span><span>Recettes {euro(receipts)}</span><span>Dépenses {euro(expenses)}</span><strong>Résultat {euro(receipts-expenses)}</strong></div>}<p>Tâches : {ts.filter(t=>t.status==='Terminé').length}/{ts.length} terminées</p><button className="textbutton" onClick={()=>setSelectedProject(p)}>Ouvrir l'opération <ArrowRight size={15}/></button></article>})}{projects.length===0&&<p>Aucune opération créée.</p>}</div></div>
 {selectedIdea&&<div className="op-overlay" onClick={()=>setSelectedIdea(null)}><div className="op-dialog" onClick={e=>e.stopPropagation()}><button className="op-close" onClick={()=>setSelectedIdea(null)}>Fermer ×</button><span className="tag">{selectedIdea.status}</span><h2>{selectedIdea.title}</h2><p>{selectedIdea.description||'Aucune description'}</p><p className="muted">Référent : {selectedIdea.source==='public'?(selectedIdea.contact_name||'Parent'):members.find(m=>m.id===selectedIdea.author_id)?.full_name||'Membre du bureau'}</p><h3>Commentaires</h3>{comments.map(c=><div className="op-comment" key={c.id}><strong>{members.find(m=>m.id===c.author_id)?.full_name||'Membre du bureau'}</strong><small>{new Date(c.created_at).toLocaleString('fr-FR')}</small><p>{c.body}</p></div>)}<form onSubmit={postComment}><textarea required value={comment} onChange={e=>setComment(e.target.value)} placeholder="Écrire un commentaire…"/><button className="primary">Publier le commentaire</button></form>{isManager&&<button className="primary" onClick={()=>{setConvertIdea(selectedIdea);start(selectedIdea)}}><CheckCircle2 size={16}/> Transformer en opération</button>}</div></div>}
 {selectedProject&&<div className="op-overlay" onClick={()=>setSelectedProject(null)}><div className="op-dialog" onClick={e=>e.stopPropagation()}><button className="op-close" onClick={()=>setSelectedProject(null)}>Fermer ×</button><h2>{selectedProject.title}</h2><p>{selectedProject.description}</p><p>Budget prévisionnel : {euro(Number(selectedProject.budget||0))}</p><label>Statut <select value={selectedProject.status} onChange={e=>void setProjectStatus(selectedProject,e.target.value)}>{['À étudier','Planifié','En cours','Terminé','Suspendu','Abandonné'].map(v=><option key={v}>{v}</option>)}</select></label><h3>Checklist</h3>{tasks.filter(t=>t.project_id===selectedProject.id).map(t=><div className="op-task" key={t.id}><span>{t.title}<small> · {members.find(m=>m.id===t.assignee_id)?.full_name||'Non attribuée'} · {t.due_date||'Sans échéance'}</small></span><select value={t.status} onChange={e=>void updateTask(t,e.target.value)}>{['À faire','En cours','Terminé','Abandonné'].map(v=><option key={v}>{v}</option>)}</select></div>)}<form onSubmit={addTask}><input name="task" placeholder="Nouvelle tâche" required/><select name="assignee" required><option value="">Responsable de la tâche</option>{members.map(m=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select><input name="due" type="date" required/><button className="primary"><Plus size={16}/> Ajouter une tâche</button></form><p className="muted">Les recettes et dépenses de cette opération se saisissent dans Finances en sélectionnant son nom.</p></div></div>}
 {showCreate&&<div className="op-overlay" onClick={()=>setShowCreate(false)}><div className="op-dialog" onClick={e=>e.stopPropagation()}><button className="op-close" onClick={()=>setShowCreate(false)}>Fermer ×</button><h2>{convertIdea?'Transformer une idée':'Nouvelle opération'}</h2><form onSubmit={convert}><label>Nom<input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Description<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Responsable<select required value={draft.owner_id} onChange={e=>setDraft({...draft,owner_id:e.target.value})}><option value="">Sélectionner</option>{members.map(m=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select></label><label>Autres membres du bureau (plusieurs choix)<select multiple value={draft.members} onChange={e=>setDraft({...draft,members:Array.from(e.currentTarget.selectedOptions).map(x=>x.value)})}>{members.filter(m=>m.id!==draft.owner_id).map(m=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select></label><label>Autres bénévoles (noms séparés par une virgule)<input placeholder="Ex. Marie Dupont, Jean Martin" value={draft.volunteers} onChange={e=>setDraft({...draft,volunteers:e.target.value})}/></label><label>Échéance<input type="date" value={draft.deadline} onChange={e=>setDraft({...draft,deadline:e.target.value})}/></label><label>Budget prévisionnel (€)<input type="number" min="0" step="0.01" value={draft.budget} onChange={e=>setDraft({...draft,budget:e.target.value})}/></label><h3>Premières tâches</h3>{draft.tasks.map((t,i)=><div key={i} className="op-task-draft"><input placeholder={`Tâche ${i+1}`} value={t.title} onChange={e=>setDraft({...draft,tasks:draft.tasks.map((x,j)=>i===j?{...x,title:e.target.value}:x)})}/><select value={t.assignee_id} onChange={e=>setDraft({...draft,tasks:draft.tasks.map((x,j)=>i===j?{...x,assignee_id:e.target.value}:x)})}><option value="">Personne responsable</option>{members.map(m=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select><input type="date" value={t.due_date} onChange={e=>setDraft({...draft,tasks:draft.tasks.map((x,j)=>i===j?{...x,due_date:e.target.value}:x)})}/></div>)}<button type="button" onClick={()=>setDraft({...draft,tasks:[...draft.tasks,blankTask()]})}>+ Ajouter une tâche</button><button disabled={busy} className="primary">{busy?'Création…':'Créer l’opération'}</button></form></div></div>}
 </section>
}
