import {useCallback,useEffect,useMemo,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
import './commissions.css';
type Item=Record<string,any>;
type Props={db:SupabaseClient;userId:string;isBureau:boolean;canManage:boolean};
const sections=['Tableau de bord','Finances','Tâches','Sponsors','Bénévoles','Planning','Matériel','Documents','Équipe'] as const;
const tables:Record<string,string>={'Finances':'commission_finances','Tâches':'commission_tasks','Sponsors':'commission_sponsors','Bénévoles':'commission_volunteers','Planning':'commission_schedule','Matériel':'commission_equipment','Documents':'commission_documents','Équipe':'commission_members'};
const fields:Record<string,{key:string;label:string;type?:string;options?:string[]}[]>={
'Finances':[{key:'label',label:'Libellé'},{key:'kind',label:'Type',options:['dépense','recette']},{key:'amount',label:'Montant (€)',type:'number'},{key:'category',label:'Catégorie'},{key:'status',label:'Statut',options:['prévu','engagé','payé','encaissé']},{key:'date',label:'Date',type:'date'},{key:'notes',label:'Notes'}],
'Tâches':[{key:'title',label:'Tâche'},{key:'description',label:'Description'},{key:'assignee_id',label:'Responsable (identifiant du membre)'},{key:'due_date',label:'Échéance',type:'date'},{key:'priority',label:'Priorité',options:['basse','normale','haute']},{key:'status',label:'Statut',options:['à faire','en cours','terminée']}],
'Sponsors':[{key:'name',label:'Entreprise'},{key:'contact_name',label:'Contact'},{key:'email',label:'E-mail',type:'email'},{key:'phone',label:'Téléphone'},{key:'amount_expected',label:'Montant espéré (€)',type:'number'},{key:'amount_received',label:'Montant encaissé (€)',type:'number'},{key:'contribution',label:'Contrepartie ou don en nature'},{key:'status',label:'Statut',options:['identifié','contacté','en discussion','confirmé','payé','refusé']},{key:'notes',label:'Historique et commentaires'}],
'Bénévoles':[{key:'full_name',label:'Nom complet'},{key:'email',label:'E-mail',type:'email'},{key:'phone',label:'Téléphone'},{key:'assignment',label:'Rôle / affectation'},{key:'availability',label:'Disponibilités'},{key:'notes',label:'Informations utiles'}],
'Planning':[{key:'title',label:'Action'},{key:'starts_at',label:'Début',type:'datetime-local'},{key:'ends_at',label:'Fin',type:'datetime-local'},{key:'location',label:'Lieu'},{key:'responsible',label:'Responsable'},{key:'notes',label:'Notes'}],
'Matériel':[{key:'name',label:'Matériel'},{key:'quantity',label:'Quantité',type:'number'},{key:'owner',label:'Propriétaire / fournisseur'},{key:'responsible',label:'Responsable'},{key:'status',label:'Statut',options:['à trouver','réservé','disponible','rendu']},{key:'notes',label:'Notes'}],
'Documents':[{key:'title',label:'Titre'},{key:'url',label:'Lien vers le document',type:'url'},{key:'category',label:'Catégorie'},{key:'notes',label:'Notes'}],
'Équipe':[{key:'email',label:'Adresse e-mail du compte',type:'email'},{key:'role',label:'Rôle',options:['member','manager']},{key:'status',label:'Accès',options:['active','revoked']}]
};
const fmt=(n:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(n||0);
const label=(r:Item,section:string)=>String(r.title||r.label||r.name||r.full_name||r.email||'Élément');
export default function CommissionsModule({db,userId,isBureau,canManage}:Props){
 const [applications,setApplications]=useState<Item[]>([]),[publishing,setPublishing]=useState(false),[commissions,setCommissions]=useState<Item[]>([]),[memberships,setMemberships]=useState<Item[]>([]),[selected,setSelected]=useState(''),[tab,setTab]=useState<string>('Tableau de bord'),[items,setItems]=useState<Item[]>([]),[finances,setFinances]=useState<Item[]>([]),[tasks,setTasks]=useState<Item[]>([]),[sponsors,setSponsors]=useState<Item[]>([]),[volunteers,setVolunteers]=useState<Item[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<Item|null>(null),[form,setForm]=useState<Record<string,string>>({}),[commissionForm,setCommissionForm]=useState(false),[manageAccess,setManageAccess]=useState(false);
 const current=commissions.find(c=>c.id===selected);const membership=memberships.find(m=>m.commission_id===selected&&m.user_id===userId&&m.status==='active');const canEdit=isBureau||membership?.role==='manager'||membership?.role==='member';const canEditTeam=canManage||membership?.role==='manager';
 const refresh=useCallback(async()=>{const [c,m]=await Promise.all([db.from('commissions').select('*').order('created_at',{ascending:false}),db.from('commission_members').select('*')]);if(c.error)setMessage(c.error.message);setCommissions(c.data||[]);setMemberships(m.data||[])},[db]);
 useEffect(()=>{void refresh()},[refresh]);
 useEffect(()=>{if(!selected&&commissions.length)setSelected(commissions[0].id);if(selected&&commissions.length&&!commissions.some(c=>c.id===selected))setSelected(commissions[0].id)},[commissions,selected]);
 const load=useCallback(async()=>{if(!selected)return;const all=await Promise.all(['commission_finances','commission_tasks','commission_sponsors','commission_volunteers',tables[tab]].map(t=>db.from(t).select('*').eq('commission_id',selected).order('created_at',{ascending:false})));setFinances(all[0].data||[]);setTasks(all[1].data||[]);setSponsors(all[2].data||[]);setVolunteers(all[3].data||[]);setItems(all[4].data||[]);const requests=await db.from('commission_volunteer_applications').select('*').eq('commission_id',selected).order('created_at',{ascending:false});setApplications(requests.data||[]);const error=all.find(a=>a.error)?.error;if(error)setMessage(error.message);if(requests.error)setMessage('Lecture des candidatures impossible : '+requests.error.message)},[db,selected,tab]);
 useEffect(()=>{void load();if(!selected)return;const timer=window.setInterval(()=>void load(),15000);return()=>window.clearInterval(timer)},[load]);
 const totals=useMemo(()=>({income:finances.filter(x=>x.kind==='recette'&&x.status==='encaissé').reduce((a,x)=>a+Number(x.amount||0),0),expense:finances.filter(x=>x.kind==='dépense'&&x.status==='payé').reduce((a,x)=>a+Number(x.amount||0),0),committed:finances.filter(x=>x.kind==='dépense'&&x.status==='engagé').reduce((a,x)=>a+Number(x.amount||0),0)}),[finances]);
 async function saveCommission(e:React.FormEvent){e.preventDefault();setBusy(true);const payload={name:form.name,description:form.description||null,objective:form.objective||null,event_date:form.event_date||null,budget:Number(form.budget||0),status:form.status||'préparation'};const res=editing?.id?await db.from('commissions').update(payload).eq('id',editing.id):await db.from('commissions').insert(payload).select('id').single();setBusy(false);if(res.error){setMessage(res.error.message);return}setCommissionForm(false);setEditing(null);setForm({});await refresh();if(res.data?.id)setSelected(res.data.id)}
 async function saveItem(e:React.FormEvent){e.preventDefault();if(!selected)return;setBusy(true);setMessage('');const payload:Item={commission_id:selected};for(const f of fields[tab]||[]){const val=(form[f.key]??f.options?.[0])?.trim();if(val!==undefined&&val!=='')payload[f.key]=f.type==='number'?Number(val):val;else if(editing?.id)payload[f.key]=null}let error:any=null;
 if(tab==='Équipe'&&!editing){const r=await db.rpc('commission_add_member',{p_commission_id:selected,p_email:String(payload.email||''),p_role:String(payload.role||'member')});error=r.error}
 else{const res=editing?.id?await db.from(tables[tab]).update(payload).eq('id',editing.id):await db.from(tables[tab]).insert(payload);error=res.error}
 setBusy(false);if(error){setMessage(error.message);return}setEditing(null);setForm({});setManageAccess(false);await load();await refresh()}
 async function removeItem(id:string){if(!window.confirm('Supprimer cet élément ?'))return;const res=await db.from(tables[tab]).delete().eq('id',id);if(res.error)setMessage(res.error.message);else await load()}
 async function setPublicRecruitment(enabled:boolean){if(!current||!canEditTeam)return;setPublishing(true);const r=await db.from('commissions').update({volunteer_recruitment_open:enabled}).eq('id',selected);setPublishing(false);if(r.error)setMessage(r.error.message);else await refresh()}
 async function reviewApplication(request:Item,approve:boolean){if(!canEdit)return;setBusy(true);setMessage('');const r=await db.rpc('commission_review_volunteer_application',{p_application_id:request.id,p_approve:approve});setBusy(false);if(r.error)setMessage(r.error.message);else await load()}
 async function removeCommission(){if(!current||!canManage||!window.confirm('Supprimer définitivement cette commission et toutes ses données ?'))return;const r=await db.from('commissions').delete().eq('id',current.id);if(r.error)setMessage(r.error.message);else{setSelected('');await refresh()}}
 const begin=(item:Item|null=null)=>{setEditing(item);setForm(item?Object.fromEntries(Object.entries(item).map(([k,v])=>[k,v==null?'':String(v)])):{});setManageAccess(true)};
 const csv=()=>{const cols=fields[tab]?.map(f=>f.key)||[];const lines=[cols.join(';'),...items.map(r=>cols.map(c=>'"'+String(r[c]??'').replaceAll('"','""')+'"').join(';'))];const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`commission-${current?.name||'export'}-${tab}.csv`;a.click();URL.revokeObjectURL(url)};
 return <div className="cm"><div className="cm-heading"><div><span className="cm-eyebrow">ESPACE COLLABORATIF</span><h1>Commissions</h1><p>Une équipe, un événement, un budget et un suivi partagé.</p></div>{canManage&&<button className="cm-primary" onClick={()=>{setEditing(null);setForm({});setCommissionForm(true)}}>+ Nouvelle commission</button>}</div>{message&&<div className="cm-alert" role="alert">{message} <button onClick={()=>setMessage('')}>Fermer</button></div>}
 <div className="cm-layout"><aside className="cm-list"><h3>Mes commissions</h3>{commissions.map(c=><button key={c.id} className={selected===c.id?'cm-active':''} onClick={()=>{setSelected(c.id);setTab('Tableau de bord');setManageAccess(false)}}><strong>{c.name}</strong><small>{c.status||'préparation'} {c.event_date?'· '+new Date(c.event_date).toLocaleDateString('fr-FR'):''}</small></button>)}{commissions.length===0&&<p>Aucune commission accessible pour le moment.</p>}</aside>
 {current&&<div className="cm-content"><div className="cm-title"><div><h2>{current.name}</h2><p>{current.objective||current.description||'Objectif à définir'} {current.event_date&&'· '+new Date(current.event_date).toLocaleDateString('fr-FR')}</p></div>{canManage&&<div className="cm-actions"><button onClick={()=>{setEditing(current);setForm(Object.fromEntries(Object.entries(current).map(([k,v])=>[k,String(v??'')] )));setCommissionForm(true)}}>Modifier</button><button onClick={removeCommission}>Supprimer</button></div>}</div>
 <nav className="cm-tabs">{sections.filter(t=>t!=='Équipe'||canEditTeam||isBureau).map(t=><button key={t} className={tab===t?'cm-active':''} onClick={()=>{setTab(t);setManageAccess(false)}}>{t}</button>)}</nav>
 {tab==='Tableau de bord'?<><div className="cm-stats"><div><small>Budget prévisionnel</small><strong>{fmt(Number(current.budget))}</strong></div><div><small>Recettes encaissées</small><strong>{fmt(totals.income)}</strong></div><div><small>Dépenses payées</small><strong>{fmt(totals.expense)}</strong></div><div><small>Reste du budget</small><strong>{fmt(Number(current.budget)-totals.expense-totals.committed)}</strong></div></div><div className="cm-stats"><div><small>Tâches non terminées</small><strong>{tasks.filter(t=>t.status!=='terminée').length}</strong></div><div><small>Sponsors confirmés</small><strong>{sponsors.filter(s=>['confirmé','payé'].includes(s.status)).length}</strong></div><div><small>Bénévoles</small><strong>{volunteers.length}</strong></div><div><small>Dépenses engagées</small><strong>{fmt(totals.committed)}</strong></div></div><section className="cm-recruitment"><h3>Recrutement des bénévoles</h3><p>Affichez un encart « Devenir bénévole » sur le site public de l'APEL. Les candidatures sont examinées ici avant d'être ajoutées aux bénévoles.</p><label className="cm-switch"><input type="checkbox" checked={Boolean(current.volunteer_recruitment_open)} disabled={!canEditTeam||publishing} onChange={e=>void setPublicRecruitment(e.target.checked)}/> Publier l'appel à bénévoles sur le site public</label><div className="cm-recruitment-title"><h4>Demandes à examiner ({applications.filter(a=>a.status==='pending').length})</h4><button type="button" onClick={()=>void load()} disabled={busy}>Actualiser les demandes</button></div>{applications.filter(a=>a.status==='pending').length===0?<p>Aucune demande en attente.</p>:applications.filter(a=>a.status==='pending').map(a=><article key={a.id} className="cm-application"><div><strong>{a.full_name}</strong> · <a href={'mailto:'+a.email}>{a.email}</a>{a.phone&&<span> · {a.phone}</span>}{a.availability&&<p>Disponibilités : {a.availability}</p>}{a.message&&<p>{a.message}</p>}</div><div className="cm-actions"><button disabled={busy||!canEdit} onClick={()=>void reviewApplication(a,false)}>Refuser</button><button className="cm-primary" disabled={busy||!canEdit} onClick={()=>void reviewApplication(a,true)}>Accepter</button></div></article>)}</section><p className="cm-note">Les montants correspondent aux opérations saisies dans la commission. Ils ne constituent pas une écriture automatique dans la comptabilité générale de l'APEL.</p></>:<><div className="cm-toolbar"><h3>{tab}</h3><div className="cm-actions"><button onClick={csv}>Exporter CSV (Excel)</button>{(canEdit&&(tab!=='Équipe'||canEditTeam))&&<button className="cm-primary" onClick={()=>begin()}>+ Ajouter</button>}</div></div>{tab==='Équipe'&&<p className="cm-note">Pour accorder un accès, la personne doit déjà posséder un compte Supabase avec un profil actif. Un membre commission ne voit que ses commissions.</p>}
 <div className="cm-records">{items.length===0?<p>Aucune donnée dans cette rubrique.</p>:items.map(item=><article key={item.id}><div><strong>{label(item,tab)}</strong><small>{[item.status,item.category,item.assignment,item.contact_name,item.location,item.role].filter(Boolean).join(' · ')}</small>{(item.amount!==undefined||item.amount_expected!==undefined)&&<small>{fmt(Number(item.amount??item.amount_expected))}</small>}{item.email&&<a href={'mailto:'+item.email}>{item.email} ↗</a>}{item.url&&<a href={item.url} target="_blank" rel="noopener noreferrer">Ouvrir le document ↗</a>}{item.notes&&<p>{item.notes}</p>}</div><div className="cm-actions">{canEdit&&(tab!=='Équipe'||canEditTeam)&&<><button onClick={()=>begin(item)}>Modifier</button><button onClick={()=>void removeItem(item.id)}>Supprimer</button></>}</div></article>)}</div></>}
 </div>}</div>
 {commissionForm&&<div className="cm-overlay"><form className="cm-dialog" onSubmit={saveCommission}><h2>{editing?'Modifier':'Créer'} une commission</h2>{[{key:'name',label:'Nom',required:true},{key:'objective',label:'Objectif'},{key:'description',label:'Description'},{key:'event_date',label:'Date de l’événement',type:'date'},{key:'budget',label:'Budget prévisionnel (€)',type:'number'},{key:'status',label:'Statut'}].map(f=><label key={f.key}>{f.label}<input required={f.required} type={f.type||'text'} value={form[f.key]||''} onChange={e=>setForm({...form,[f.key]:e.target.value})}/></label>)}<div className="cm-actions"><button type="button" onClick={()=>setCommissionForm(false)}>Annuler</button><button className="cm-primary" disabled={busy}>Enregistrer</button></div></form></div>}
 {manageAccess&&<div className="cm-overlay"><form className="cm-dialog" onSubmit={saveItem}><h2>{editing?'Modifier':'Ajouter'} — {tab}</h2>{(fields[tab]||[]).map(f=><label key={f.key}>{f.label}{f.options?<select value={form[f.key]||f.options[0]} onChange={e=>setForm({...form,[f.key]:e.target.value})}>{f.options.map(o=><option key={o} value={o}>{o}</option>)}</select>:<input type={f.type||'text'} value={form[f.key]||''} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>}</label>)}<div className="cm-actions"><button type="button" onClick={()=>setManageAccess(false)}>Annuler</button><button className="cm-primary" disabled={busy}>Enregistrer</button></div></form></div>}
 </div>}
