import React,{useEffect,useMemo,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
type Doc={id:string;title:string;description?:string|null;created_at?:string;source:string;path?:string;bucket?:string;kind:string};
export default function DocumentsModule({db,canFinance}:{db:SupabaseClient;canFinance:boolean}){
 const [docs,setDocs]=useState<Doc[]>([]),[query,setQuery]=useState(''),[source,setSource]=useState('Tous'),[type,setType]=useState('Tous'),[message,setMessage]=useState(''),[file,setFile]=useState<File|null>(null),[uploading,setUploading]=useState(false);
 async function load(){const all:Doc[]=[];const issues:string[]=[];const legacy=await db.from('documents').select('*').order('created_at',{ascending:false}).limit(1000);if(legacy.error)issues.push('Documents : '+legacy.error.message);else (legacy.data||[]).forEach((d:any)=>all.push({id:'doc-'+d.id,title:d.title||'Sans titre',description:d.description,created_at:d.created_at,source:'Documents',kind:d.kind||'Document',path:d.storage_path||d.path,bucket:d.bucket||'apel-documents'}));
 const meetings=await db.from('meetings').select('id,title,minutes,created_at').not('minutes','is',null).order('created_at',{ascending:false}).limit(1000);if(meetings.error)issues.push('Réunions : '+meetings.error.message);else(meetings.data||[]).filter((m:any)=>m.minutes?.trim()).forEach((m:any)=>all.push({id:'meeting-'+m.id,title:'Compte rendu – '+m.title,description:m.minutes,created_at:m.created_at,source:'Réunions',kind:'Compte rendu'}));
 if(canFinance){const proofs=await db.from('finance_justificatifs').select('id,nom_fichier,storage_path,created_at').order('created_at',{ascending:false}).limit(1000);if(proofs.error)issues.push('Justificatifs : '+proofs.error.message);else(proofs.data||[]).forEach((d:any)=>all.push({id:'proof-'+d.id,title:d.nom_fichier,created_at:d.created_at,source:'Finances',kind:'Justificatif',path:d.storage_path,bucket:'finance-justificatifs'}))}
 setDocs(all);setMessage(issues.join(' · '))}
 useEffect(()=>{void load()},[db,canFinance]);
 const filtered=useMemo(()=>docs.filter(d=>(source==='Tous'||d.source===source)&&(type==='Tous'||d.kind===type)&&[d.title,d.description,d.source,d.kind].join(' ').toLocaleLowerCase('fr').includes(query.toLocaleLowerCase('fr'))),[docs,source,type,query]);
 async function open(d:Doc){if(d.path&&d.bucket){const {data,error}=await db.storage.from(d.bucket).createSignedUrl(d.path,120);if(error||!data?.signedUrl)setMessage('Ouverture impossible : '+(error?.message||'Fichier indisponible'));else window.open(data.signedUrl,'_blank','noopener,noreferrer')}else if(d.source==='Réunions'){const w=window.open('','_blank');if(w){const pre=w.document.createElement('pre');pre.textContent=d.title+'\n\n'+(d.description||'');pre.style.whiteSpace='pre-wrap';pre.style.fontFamily='system-ui';w.document.body.append(pre)}}else setMessage('Ce document ne possède pas encore de fichier associé.')} 
 async function upload(e:React.FormEvent){e.preventDefault();if(!file)return;setUploading(true);setMessage('');const path=`documents/${crypto.randomUUID()}/${file.name}`;const up=await db.storage.from('apel-documents').upload(path,file,{upsert:false});if(up.error){setMessage(up.error.message);setUploading(false);return}const ins=await db.from('documents').insert({title:file.name,description:'Fichier ajouté depuis la bibliothèque documentaire',storage_path:path,bucket:'apel-documents',kind:file.type.includes('pdf')?'PDF':'Fichier'});if(ins.error){await db.storage.from('apel-documents').remove([path]);setMessage(ins.error.message)}else{setFile(null);await load()}setUploading(false)}
 return <div><div className="eyebrow">BIBLIOTHÈQUE DU BUREAU</div><h1>Documents de l’APEL</h1><p className="lead">Retrouvez les documents, comptes rendus et justificatifs financiers autorisés pour votre rôle.</p>{message&&<p role="status" className="alert">{message}</p>}<div className="panel form"><label>Rechercher<input placeholder="Nom, contenu, catégorie…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="quick"><label>Module<select value={source} onChange={e=>setSource(e.target.value)}>{['Tous','Documents','Réunions',...(canFinance?['Finances']:[])].map(x=><option key={x}>{x}</option>)}</select></label><label>Type<select value={type} onChange={e=>setType(e.target.value)}>{['Tous',...Array.from(new Set(docs.map(d=>d.kind)))].map(x=><option key={x}>{x}</option>)}</select></label></div><p>{filtered.length} résultat(s)</p></div><form className="panel form" onSubmit={upload}><h3>Ajouter un document</h3><input type="file" required onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="primary" disabled={!file||uploading}>{uploading?'Envoi…':'Ajouter à la bibliothèque'}</button></form><div className="records">{filtered.map(d=><article className="record" key={d.id}><span className="tag">{d.source} · {d.kind}</span><h3>{d.title}</h3><p className="muted">{d.created_at?new Date(d.created_at).toLocaleDateString('fr-FR'):''}</p><button className="textbutton" onClick={()=>void open(d)}>Consulter / télécharger</button></article>)}</div>{!filtered.length&&<p>Aucun document correspondant.</p>}</div>
}
